baseURL = '/'
languageCode = 'en-us'
theme = "hugo-coder"
title = "BrandgrandReal's Blog"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "BrandgrandReal"
  info = "Hello my name is Brandon I am a coding enthusiast, gamer, And a Highschool student. I build websites, make chat bots, and have fun!"
  description = "Brandgrand's Blog"
  keywords = "blog,developer,personal"
  avatarurl = "images/PFP.png"
  #gravatar = "john.doe@example.com"

  since = 2024

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/BrandgrandRealMe/"
[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/BrandgrandReal/"

# Comment Sections
[[params.giscus]] # https://giscus.app
  repo = "BrandgrandRealMe/HugoBlog"
  repoID = "R_kgDOLaXRzw"
  category = "Blog Comments"
  categoryID = "DIC_kwDOLaXRz84Cdy-g"
  mapping = "title"
  term = ""
  strict = "0"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  theme = "preferred_color_scheme"
  lang = "en"
  loading = ""
# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
